USE dogAdoption;
GO
ALTER TABLE Customers WITH CHECK
ADD CONSTRAINT FK_Zipcode FOREIGN KEY(Zipcode) REFERENCES Zipcode(Zipcode)
ON UPDATE CASCADE
GO
ALTER TABLE Adoption WITH CHECK
ADD CONSTRAINT FK_LocationID FOREIGN KEY(LocationID) REFERENCES Locations(ID)
ON UPDATE CASCADE
GO
ALTER TABLE Adoption WITH CHECK
ADD CONSTRAINT FK_CustomerID FOREIGN KEY(CustomerID) REFERENCES Customers(ID)
ON UPDATE CASCADE
GO
ALTER TABLE AdoptionDetails WITH CHECK
ADD CONSTRAINT FK_Adoption FOREIGN KEY(Adoption) REFERENCES Adoption(ID)
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE AdoptionDetails WITH CHECK
ADD CONSTRAINT FK_DogID FOREIGN KEY(DogID) REFERENCES Dogs(DogID)
ON UPDATE CASCADE
GO

